### ISSUE TITLE
(auto-complete error: (wrong-number-of-arguments setq 1)

### ISSUE THREAD

**Issue by sunilw** [auto-complete/auto-complete#466]
I recently update from emacs24 to emacs25.
I had no problems with auto-complete-mode under emacs24.

Under emacs25 I find that auto-complete-mode exists (afaict) as soon as keyboard strokes occur in a buffer.

In the messages buffer I see this: 
(auto-complete error: (wrong-number-of-arguments setq 1)

I can re-enable it. If I do, the same thing happens: upon a keystroke, the mode exits and the same message is generated.

**Comment by phst** [comment]
This has been fixed https://github.com/auto-complete/auto-complete/pull/424; you'll need to upgrade auto-complete-mode to a more recent version.

**Comment by syohex** [comment]
Please reinstall auto-complete as @phst saied.

**Comment by jayknowstheway** [comment]
Hmm.. I just downloaded auto-complete 1.4 off the repository and still get this issue.. is the problem that the most up-to-date version is not in Marmalade?
