### ISSUE TITLE
Crash with emacs 29.1: "Error: Symbol’s value as variable is void: macro-declaration-function"

### ISSUE THREAD

**Issue by Perdu** [auto-complete/auto-complete#527]
Since updating emacs from 28.2-2 to 29.1-2, I have a crash at startup:
```Symbol's value as variable is void: macro-declaration-function```

The same goes when trying to recompile package from melpa:
```
Compiling file /home/user/.emacs.d/elpa/auto-complete-1.5.1/auto-complete-config.el at Wed Aug  2 15:36:43 2023
Entering directory ‘/home/user/.emacs.d/elpa/auto-complete-1.5.1/’
auto-complete-config.el:29:2: Error: Symbol’s value as variable is void: macro-declaration-function
```

**Comment by Perdu** [comment]
This happens with auto-complete 1.3.1 and 1.5.1.

**Comment by jcs090218** [comment]
I will look into it!

**Comment by jcs090218** [comment]
I have fixed all byte-compile warnings. Can you try clean install? Remove package from `~/.emacs.d/elpa/auto-complete-xxx/` and `M-x package-install`. Thanks!

**Comment by Perdu** [comment]
I still get the same error, even after deleting package and refreshing package contents:
```
Leaving directory ‘/home/user/.emacs.d/elpa/auto-complete-1.5.1’

Compiling file /home/user/.emacs.d/elpa/auto-complete-1.5.1/auto-complete-config.el at Thu Sep 28 18:51:09 2023
Entering directory ‘/home/user/.emacs.d/elpa/auto-complete-1.5.1/’

Compiling file /home/user/.emacs.d/elpa/auto-complete-1.5.1/auto-complete.el at Thu Sep 28 18:51:09 2023

Compiling internal form(s) at Thu Sep 28 18:51:09 2023
Error (bytecomp): Symbol’s value as variable is void: macro-declaration-function [2 times]

```

**Comment by akira-okumura** [comment]
I get the same error after upgrading Emacs 30.1 and auto-complete 20250101.843.
```
⛔ Warning (initialization): An error occurred while loading ‘/Users/oxon/.emacs.d/init.el’:

Symbol's value as variable is void: macro-declaration-function

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

```
Debugger entered--Lisp error: (void-variable macro-declaration-function)
  (if macro-declaration-function (funcall macro-declaration-function 'popup-aif '(declare (indent 2))))
  require(popup)
  require(auto-complete)
  require(auto-complete-config)
  eval-buffer(#<buffer  *load*> nil "/Users/oxon/.emacs.d/init.el" nil t)  ; Reading at buffer position 3056
  load-with-code-conversion("/Users/oxon/.emacs.d/init.el" "/Users/oxon/.emacs.d/init.el" t t)
  load("/Users/oxon/.emacs.d/init" noerror nomessage)
  #f(compiled-function () #<bytecode 0x12e013f4b08e0711>)()
  #f(compiled-function () #<bytecode -0x4307d7bb01d2857>)()
  handler-bind-1(#f(compiled-function () #<bytecode -0x4307d7bb01d2857>) (error) startup--debug)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x427dc056a930113>) #f(compiled-function () #<bytecode 0x731968ef8c3769b>) t)
  command-line()
  normal-top-level()
```
